### ISSUE TITLE
EventManager

### ISSUE THREAD

**Issue by osyka-yuri** [Riemelt/justSlider#7]
Сейчас вид и модель имеют общий объект EventManager, и соответственно они знают о событиях друг друга, вследствие чего теряется смысл презентера, так как они и так имеют доступ к событиям друг друга. Необходимо чтобы у модели и вида был собственный набор событий, на которые презентер должен подписываться и при необходимости обновлять вид и модель.

**Comment by Azmodan95** [comment]
Один нюанс, для получения функционала EventManager лучше использовать наследование, а не отдельно создавать его объект.
